// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using viavem_api.Context;

#nullable disable

namespace viavem_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("viavem_api.Models.Aeroportos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aeroportos");
                });

            modelBuilder.Entity("viavem_api.Models.Comentarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<string>("DataPublicacao")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("viavem_api.Models.Passagens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DataChegada")
                        .HasColumnType("longtext");

                    b.Property<string>("DataRetorno")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSaida")
                        .HasColumnType("longtext");

                    b.Property<int>("IdAeroporto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<float>("Preco")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdAeroporto");

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("viavem_api.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("IdPassagens")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdPassagens");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("viavem_api.Models.Comentarios", b =>
                {
                    b.HasOne("viavem_api.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("viavem_api.Models.Passagens", b =>
                {
                    b.HasOne("viavem_api.Models.Aeroportos", "Aeroportos")
                        .WithMany()
                        .HasForeignKey("IdAeroporto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aeroportos");
                });

            modelBuilder.Entity("viavem_api.Models.Usuarios", b =>
                {
                    b.HasOne("viavem_api.Models.Passagens", "Passagens")
                        .WithMany()
                        .HasForeignKey("IdPassagens")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passagens");
                });
#pragma warning restore 612, 618
        }
    }
}
